### ISSUE TITLE
 [BUG] Segmentation fault

### ISSUE THREAD

**Issue by hellmind** [vyatta4people/vyBuddy#3]
/usr/local/rvm/gems/ruby-1.9.3-head/gems/mysql2-0.3.17/lib/mysql2/mysql2.so: [BUG] Segmentation fault

vymasterd.err                                                                                                                                                                                               157/157               100%
/usr/local/rvm/gems/ruby-1.9.3-head/gems/mysql2-0.3.17/lib/mysql2/mysql2.so: [BUG] Segmentation fault
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

on
/opt/vybuddy/log

**Comment by vyatta4people** [comment]
Hi,

Looks like ruby symlink broken! Have you run "update-vybuddy" script in the appliance shell? 
It pulls and applies all the fixes!

**Comment by hellmind** [comment]
Sure, serveral times
Also i tried to update ubuntu
Also I reinstalled the mysql2 package

I think I got 2 ruby versions.
What can I try?

**Comment by vyatta4people** [comment]
Run in shell: 
1) which ruby
2) ls -l /usr/bin/ruby
3) ls -l /etc/alternatives/ruby

post back output here

**Comment by hellmind** [comment]
root@vybuddy:/opt/vybuddy/log# which ruby
/usr/bin/ruby
root@vybuddy:/opt/vybuddy/log# ls -l /usr/bin/ruby
lrwxrwxrwx 1 root root 22 Jan 23 01:44 /usr/bin/ruby ->
/etc/alternatives/ruby
root@vybuddy:/opt/vybuddy/log# ls -l /etc/alternatives/ruby
lrwxrwxrwx 1 root root 16 Jan 23 01:44 /etc/alternatives/ruby ->
/usr/bin/ruby1.8

**Comment by vyatta4people** [comment]
*Hm... All these must be fixed by "update-vybuddy" script...*

Please run this manually on vyBuddy appliance:
sudo rm -f /usr/bin/ruby
sudo ln -s /usr/local/rvm/rubies/ruby-1.9.3-head/bin/ruby /usr/bin/ruby
sudo update-alternatives --remove-all ruby

Then restart appliance and check.

**Comment by hellmind** [comment]
using update-vybuddy:
vybuddy@vybuddy:~$ update-vybuddy
[ PRE-DEPLOY ]
* Stopping application server
 * Stopping web server apache2


    ... waiting

                                                                          [
OK ]
* Stopping vyBuddy daemon
/usr/local/sbin/vybuddyctl: line 42: kill: (6945) - No such process
[ DEPLOY ]
* Deploying project from GitHub
(Backtrace restricted to imported tasks)
cap aborted!
LoadError: cannot load such file -- config/deploy
/opt/vybuddy/rails/Capfile:8:in `load'
/opt/vybuddy/rails/Capfile:8:in `<top (required)>'
(See full trace by running task with --trace)
(Backtrace restricted to imported tasks)
cap aborted!
OptionParser::AmbiguousOption: ambiguous option: -s

(See full trace by running task with --trace)
* Copying database.yml
* Updating bundle
Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from http://rubygems.org/..
Using rake (10.4.2)
Using i18n (0.6.1)
Using multi_json (1.10.1)
Using activesupport (3.2.13)
Using builder (3.0.4)
Using activemodel (3.2.13)
Using erubis (2.7.0)
Using journey (1.0.4)
Using rack (1.4.5)
Using rack-cache (1.2)
Using rack-test (0.6.3)
Using hike (1.2.3)
Using tilt (1.4.1)
Using sprockets (2.2.3)
Using actionpack (3.2.13)
Using mime-types (1.25.1)
Using polyglot (0.3.5)
Using treetop (1.4.15)
Using mail (2.5.4)
Using actionmailer (3.2.13)
Using arel (3.0.3)
Using tzinfo (0.3.42)
Using activerecord (3.2.13)
Using activeresource (3.2.13)
Using bundler (1.2.1)
Using capistrano-stats (1.1.1)
Using colorize (0.7.5)
Using net-ssh (2.9.2)
Using net-scp (1.2.1)
Using sshkit (1.6.1)
Using capistrano (3.3.5)
Using coffee-script-source (1.8.0)
Using execjs (2.2.2)
Using coffee-script (2.3.0)
Using rack-ssl (1.3.4)
Using json (1.8.2)
Using rdoc (3.12.2)
Using thor (0.19.1)
Using railties (3.2.13)
Using coffee-rails (3.2.2)
Using daemon_controller (1.2.0)
Using directory_template (1.0.1)
Using htmlentities (4.3.3)
Using jquery-rails (3.1.2)
Using libv8 (3.16.14.7)
Using mysql2 (0.3.17)
Using net-sftp (2.1.2)
Using netzke-core (0.7.7)
Using netzke-basepack (0.7.7)
Using passenger (4.0.58)
Using rails (3.2.13)
Using ref (1.0.5)
Using rinku (1.7.3)
Using rvm (1.11.3.9)
Using sass (3.4.10)
Using sass-rails (3.2.6)
Using therubyracer (0.12.1)
Using uglifier (2.7.0)
Your bundle is updated! Use `bundle show [gemname]` to see where a bundled
gem is installed.
[ CUSTOM ]
* Running custom update script
* Setting executable permissions on daemons and scripts
[ POST-DEPLOY ]
* Starting vyBuddy daemon
lib/daemons/vymasterd.rb
* Starting application server
 * Starting web server apache2

                                                                        [
OK ]
vybuddy@vybuddy:~$ which ruby
/usr/local/rvm/rubies/ruby-1.9.3-head/bin/ruby
vybuddy@vybuddy:~$ ls -l /usr/bin/ruby
lrwxrwxrwx 1 root root 22 Jan 23 01:44 /usr/bin/ruby ->
/etc/alternatives/ruby
vybuddy@vybuddy:~$ ls -l /etc/alternatives/ruby
lrwxrwxrwx 1 root root 16 Jan 23 01:44 /etc/alternatives/ruby ->
/usr/bin/ruby1.8

After
sudo rm -f /usr/bin/ruby
sudo ln -s /usr/local/rvm/rubies/ruby-1.9.3-head/bin/ruby /usr/bin/ruby
sudo update-alternatives --remove-all ruby
sudo reboot

I still get : Not applicable to this host... on web gui.

vybuddy@vybuddy:~$ which ruby
vybuddy@vybuddy:~$ ls -l /usr/bin/ruby
ls: cannot access /usr/bin/ruby: No such file or directory
vybuddy@vybuddy:~$ ls -l /usr/bin/ruby
ls: cannot access /usr/bin/ruby: No such file or directory

Then I did:
vybuddy@vybuddy:~$ update-vybuddy
[ PRE-DEPLOY ]
* Stopping application server
 * Stopping web server apache2


    ... waiting

                                                                          [
OK ]
* Stopping vyBuddy daemon
/usr/local/sbin/vybuddyctl: line 42: kill: (895) - No such process
[ DEPLOY ]
* Deploying project from GitHub
  * 2015-01-24 07:48:02 executing `deploy'
  * 2015-01-24 07:48:02 executing `deploy:update'
 ** transaction: start
  * 2015-01-24 07:48:02 executing `deploy:update_code'
    updating the cached checkout on all servers
    executing locally: "git ls-remote
https://github.com/vyatta4people/vyBuddy.git master"
    command finished in 570ms
  * executing "if [ -d /opt/vybuddy/rails/shared/cached-copy ]; then cd
/opt/vybuddy/rails/shared/cached-copy && git fetch -q origin && git fetch
--tags -q origin && git reset -q --hard
8c094eace91172c02facaceded7ffe3832e5340e && git clean -q -d -x -f; else git
clone -q -b master https://github.com/vyatta4people/vyBuddy.git
/opt/vybuddy/rails/shared/cached-copy && cd
/opt/vybuddy/rails/shared/cached-copy && git checkout -q -b deploy
8c094eace91172c02facaceded7ffe3832e5340e; fi"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
    command finished in 7224ms
    copying the cached version to /opt/vybuddy/rails/releases/20150124104810
  * executing "cp -RPp /opt/vybuddy/rails/shared/cached-copy
/opt/vybuddy/rails/releases/20150124104810 && (echo
8c094eace91172c02facaceded7ffe3832e5340e >
/opt/vybuddy/rails/releases/20150124104810/REVISION)"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
    command finished in 16896ms
  * 2015-01-24 07:48:27 executing `deploy:finalize_update'
  * executing "chmod -R -- g+w /opt/vybuddy/rails/releases/20150124104810
&& rm -rf -- /opt/vybuddy/rails/releases/20150124104810/public/system &&
mkdir -p -- /opt/vybuddy/rails/releases/20150124104810/public/ && ln -s --
/opt/vybuddy/rails/shared/system
/opt/vybuddy/rails/releases/20150124104810/public/system && rm -rf --
/opt/vybuddy/rails/releases/20150124104810/log && ln -s --
/opt/vybuddy/rails/shared/log
/opt/vybuddy/rails/releases/20150124104810/log && rm -rf --
/opt/vybuddy/rails/releases/20150124104810/tmp/pids && mkdir -p --
/opt/vybuddy/rails/releases/20150124104810/tmp/ && ln -s --
/opt/vybuddy/rails/shared/pids
/opt/vybuddy/rails/releases/20150124104810/tmp/pids"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
    command finished in 38ms
  * 2015-01-24 07:48:27 executing `deploy:create_symlink'
  * executing "sudo -p 'sudo password: ' rm -f /opt/vybuddy/rails/current
&& sudo -p 'sudo password: ' ln -s
/opt/vybuddy/rails/releases/20150124104810 /opt/vybuddy/rails/current"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
    command finished in 12ms
 ** transaction: commit
  * 2015-01-24 07:48:27 executing `deploy:restart'
  * 2015-01-24 07:48:28 executing `deploy:cleanup'
  * executing "sudo -p 'sudo password: ' ls -1dt
/opt/vybuddy/rails/releases/* | tail -n +3 | sudo -p 'sudo password: '
xargs rm -rf"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
    command finished in 1064ms
* Copying database.yml
* Updating bundle
Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from http://rubygems.org/..
Installing rake (10.4.2)
Using i18n (0.6.1)
Installing multi_json (1.10.1)
Using activesupport (3.2.13)
Using builder (3.0.4)
Using activemodel (3.2.13)
Using erubis (2.7.0)
Using journey (1.0.4)
Using rack (1.4.5)
Using rack-cache (1.2)
Installing rack-test (0.6.3)
Installing hike (1.2.3)
Using tilt (1.4.1)
Installing sprockets (2.2.3)
Using actionpack (3.2.13)
Installing mime-types (1.25.1)
Installing polyglot (0.3.5)
Installing treetop (1.4.15)
Using mail (2.5.4)
Using actionmailer (3.2.13)
Installing arel (3.0.3)
Installing tzinfo (0.3.42)
Using activerecord (3.2.13)
Using activeresource (3.2.13)
Using bundler (1.2.1)
Installing capistrano-stats (1.1.1)
Installing colorize (0.7.5)
Installing net-ssh (2.9.2)
Installing net-scp (1.2.1)
Installing sshkit (1.6.1)
Installing capistrano (3.3.5)
*Gem::InstallError: capistrano requires Ruby version >= 1.9.3.*
*An error occurred while installing capistrano (3.3.5), and Bundler cannot
continue.*
*Make sure that `gem install capistrano -v '3.3.5'` succeeds before
bundling.*
[ CUSTOM ]
* Running custom update script
* Setting executable permissions on daemons and scripts
[ POST-DEPLOY ]
* Starting vyBuddy daemon
lib/daemons/vymasterd.rb
* Starting application server
 * Starting web server apache2

                                                                        [
OK ]
vybuddy@vybuddy:~$

*But on web gui:*
Could not find rake-10.0.4 in any of the sources
(Bundler::GemNotFound)Exception
class:PhusionPassenger::UnknownErrorApplication root:
/opt/vybuddy/rails/currentBacktrace:#FileLineLocation0
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/spec_set.rb90in `block in materialize'1
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/spec_set.rb83in `map!'2
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/spec_set.rb83in `materialize'3
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/definition.rb113in `specs'4
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/definition.rb158in `specs_for'5
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/definition.rb147in `requested_specs'6
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/environment.rb23in `requested_specs'7
/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/runtime.rb11in `setup'8
/usr/local/rvm/gems/ruby-1.9.3-head@global/gems/bundler-1.2.1/lib/bundler.rb
116in `setup'9/usr/local/rvm/gems/ruby-1.9.3-head@global
/gems/bundler-1.2.1/lib/bundler/setup.rb17in `'10
/usr/local/rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
60in `require'11
/usr/local/rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
60in `rescue in require'12
/usr/local/rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
35in `require'13
/opt/vybuddy/rails/releases/20150124104810/config/setup_load_paths.rb14in `'
14
/usr/local/rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
36in `require'15
/usr/local/rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
36in `require'16
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/utils.rb
301in `prepare_app_process'17
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/rack/application_spawner.rb
156in `block in initialize_server'18
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/utils.rb
563in `report_app_init_status'19
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/rack/application_spawner.rb
154in `initialize_server'20
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb
204in `start_synchronously'21
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb
180in `start'22
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/rack/application_spawner.rb
129in `start'23
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb
253in `block (2 levels) in spawn_rack_application'24
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server_collection.rb
132in `lookup_or_add'25
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb
246in `block in spawn_rack_application'26
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server_collection.rb
82in `block in synchronize'27prelude>10:in `synchronize'28
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server_collection.rb
79in `synchronize'29
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb
244in `spawn_rack_application'30
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb
137in `spawn_application'31
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb
275in `handle_spawn_application'32
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb
357in `server_main_loop'33
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb
206in `start_synchronously'34
/usr/local/rvm/gems/ruby-1.9.3-head/gems/passenger-3.0.17/helper-scripts/passenger-spawn-server
99in `'
And log says:
nice: lib/daemons/vymasterd.rb: No such file or directory

**Comment by vyatta4people** [comment]
OK, now please ensure that
/usr/bin/ruby symlink points to
/usr/local/rvm/rubies/ruby-1.9.3-head/bin/ruby
Just checked out, it may got screwed by "update-alternatives".. :(

Just in case: could you provide me with SSH access to this VM?

**Comment by hellmind** [comment]
I created a symlink,, same error.
Sure, where should I send you the access info?

**Comment by vyatta4people** [comment]
cartman@cyberlynx.eu

**Comment by hellmind** [comment]
I ve sent you an email hellmind@gmail.com

**Comment by vyatta4people** [comment]
Yes. I saw it. Now have some spare time to deal with it :)

**Comment by vyatta4people** [comment]
OK, it looks like RVM environment was screwed up for unknown reason :)
Never spotted such bug, but it looks like upgrading RVM saved the day:
\curl -sSL https://get.rvm.io | sudo bash -s stable

Please see, if everything works now!

**Comment by hellmind** [comment]
Why on some tabs i get:
operational :: show dhcp leases | AS-IS

Invalid command: show dhcp [leases]

**Comment by vyatta4people** [comment]
Using the task WWW interface locate a command responsible for this and change
dhcp leases
to
dhcp server leases

Syntax changed in new Vyatta/VyOS.
I hope I will be able to apply changes
and switch to manifest-driven deploy
some day :) Now too busy...

**Comment by hellmind** [comment]
Thank you!

**Comment by vyatta4people** [comment]
Dear hellmind,

please tell me, if your issue is solved.

Any vyBuddy feedback is also welcome :)

**Comment by hellmind** [comment]
Everything is solve,
I was thinking in use vbuddy to modify the dhcp static leases in an easy
way.
Can I do that with vybuddy?

**Comment by vyatta4people** [comment]
hmmm... Easy? NO :(
